# Basic
name:               "SENSE Lab"
title:              "SENSE Lab at The Ohio State University"
description:        "This is the home-page for Ertin's SENSE Lab, we are comptational neurosciece and datascience lab at the University of Pennsylvania, Philadelphia"


# URL
url:                http://SENSE-Lab-OSU.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "blog"
    href:           "/blog"
  - name:           "resources"
    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html